### ISSUE TITLE
"Class 'Form' not found"

### ISSUE THREAD

**Issue by dubstrong** [codestudiollc/laravel-totem#68] opened 2017-12-22 18:52 UTC
Class 'Form' not found (View: C:\laragon\www\blog\vendor\studio\laravel-totem\resources\views\tasks\index.blade.php)

i get it for first time i've installed

**Comment by qschmick** [comment] 2017-12-22 19:01
Duplicate of #65

**Closed as completed by qschmick** 2017-12-22 19:01 UTC
Labels: duplicate
