### ISSUE TITLE
The "1" argument does not exist.

### ISSUE THREAD

**Issue by prakhargvp** [codestudiollc/laravel-totem#146] opened 2019-03-20 04:53 UTC
## Version information
 - Laravel: 5.8.*
 - PHP: 7.1.3
- laravel-totem: 5.0
## Description

Getting Error "The "1" argument does not exist."
## Screenshots

![Screenshot from 2019-03-20 10-16-43](https://user-images.githubusercontent.com/7056772/54659883-cee5f580-4af9-11e9-8f30-1a06e62ffa2d.png)
![Screenshot from 2019-03-20 10-16-49](https://user-images.githubusercontent.com/7056772/54659885-cf7e8c00-4af9-11e9-811a-0f231c2864dc.png)
![Screenshot from 2019-03-20 10-18-14](https://user-images.githubusercontent.com/7056772/54659886-d0172280-4af9-11e9-9b7d-400aca248725.png)
![Screenshot from 2019-03-20 10-19-03](https://user-images.githubusercontent.com/7056772/54659887-d1484f80-4af9-11e9-86fc-a5049b97bd20.png)

**Comment by roshangautam** [comment] 2019-04-07 19:16
I tried reproducing this using a command with parameters that follow the same pattern as yours and it worked fine. As I dont have access to your codebase, I would appreciate If you can help me debug this and try to figure out the root cause of the issue. I feel like this is caused by something on your end.

**Comment by Dbunny** [comment] 2019-09-23 11:02
Hi, I'm getting that same message did you manage to find a solutions please? thanks

**Comment by qschmick** [comment] 2019-10-15 15:36
@prakhargvp or @Dbunny, This was an issue was we were not handling a single `-` but only the standard double `--`. This PR should fix https://github.com/codestudiohq/laravel-totem/pull/193

**Comment by roshangautam** [comment] 2019-10-25 03:25
good catch @qschmick . Closing this now. Feel free to reopen if the issue resurfaces

**Closed as completed by roshangautam** 2019-10-25 03:25 UTC
