### ISSUE TITLE
Page isn't refreshing after execute task manually

### ISSUE THREAD

**Issue by LeandroVCastro** [codestudiollc/laravel-totem#140] opened 2019-01-24 13:26 UTC
The Totem page isn't refreshing automatic when execute a task manually. I'm needing press F5 to reload and see new logs...

Anybody else with the same problem?

**Comment by roshangautam** [comment] 2019-03-03 19:30
This is by design. Currently real time refresh is not implemented. Closing this to honor #137

**Closed as completed by roshangautam** 2019-03-03 19:30 UTC

**Comment by LeandroVCastro** [comment] 2019-03-08 12:03
Do you could explain the reason for it, please?
